### ISSUE TITLE
bugly版本更新

### ISSUE THREAD

**Issue by idootop** [crazecoder/flutter_bugly#102]
可以升级下bugly版本到最新
![图片](https://user-images.githubusercontent.com/35302658/104997179-1cb84580-5a64-11eb-89eb-c7557c174cb1.png)

<img width="918" alt="图片" src="https://user-images.githubusercontent.com/35302658/104997470-97816080-5a64-11eb-986b-ef5ee2f51fec.png">

很棒的插件，多谢作者^^

**Comment by crazecoder** [comment]
2cd2bd8c14377691e4c8991e665f129a31c1915d pub库已更新
