### ISSUE TITLE
权限配置

### ISSUE THREAD

**Issue by idootop** [crazecoder/flutter_bugly#103]
![图片](https://user-images.githubusercontent.com/35302658/104997792-2aba9600-5a65-11eb-86d5-7d34ea6777c4.png)

<img width="945" alt="图片" src="https://user-images.githubusercontent.com/35302658/104997747-18d8f300-5a65-11eb-83a2-a3ef78bb802b.png">

麻烦老哥在manifest里配置下权限，谢谢

**Comment by crazecoder** [comment]
aar自动合并，不用手动添加
