### ISSUE TITLE
MultiDex处理问题

### ISSUE THREAD

**Issue by idootop** [crazecoder/flutter_bugly#104]
<img width="903" alt="图片" src="https://user-images.githubusercontent.com/35302658/104997962-6ead9b00-5a65-11eb-8e04-5d475cd6bb6e.png">

如果项目拆分成MultiDex，该咋个处理，官方文档没看太明白，
还有符号表是咋个处理的？求问

<img width="908" alt="图片" src="https://user-images.githubusercontent.com/35302658/104998389-17f49100-5a66-11eb-8ce0-027d0023128d.png">

**Comment by crazecoder** [comment]
如果对官方文档不太明白，个人建议加官方群了解一下
