### ISSUE TITLE
启动时一堆不影响运行的报错是什么鬼

### ISSUE THREAD

**Issue by shingohu** [crazecoder/flutter_bugly#11]
W/CrashReport(29438): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
W/CrashReport(29438):   at com.tencent.bugly.crashreport.common.info.AppInfo.i(BUGLY:471)                           
W/CrashReport(29438):   at com.tencent.bugly.crashreport.common.info.AppInfo.g(BUGLY:496)                           
W/CrashReport(29438):   at com.tencent.bugly.crashreport.common.info.a.T(BUGLY:1074)                                
W/CrashReport(29438):   at com.tencent.bugly.proguard.ah.a(BUGLY:295)                                               
W/CrashReport(29438):   at com.tencent.bugly.crashreport.biz.a.c(BUGLY:286)                                         
W/CrashReport(29438):   at com.tencent.bugly.crashreport.biz.a.a(BUGLY:35)                                          
W/CrashReport(29438):   at com.tencent.bugly.crashreport.biz.a$2.run(BUGLY:335)                                     
W/CrashReport(29438):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)                  
W/CrashReport(29438):   at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                 
W/CrashReport(29438):   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/CrashReport(29438):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)          
W/CrashReport(29438):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)          
W/CrashReport(29438):   at java.lang.Thread.run(Thread.java:764)

**Comment by crazecoder** [comment]
原生bugly也会报的，我也不知道什么鬼。。。
