### ISSUE TITLE
检查升级,设置不弹toast提示, 在debug模式下生效.在release包不生效

### ISSUE THREAD

**Issue by ddswez** [crazecoder/flutter_bugly#110]
FlutterBugly.checkUpgrade(isManual: false, isSilence: true); 
在App启动时, 检查更新, 期望是不弹toast提示. 在debug包下是生效的,不弹提示. 但是在 release 包会提示,"当前已是最新版本"

**Comment by crazecoder** [comment]
还存在这个问题吗？试下autoCheckUpgrade方法

**Comment by GoogleJ** [comment]
> 还存在这个问题吗？试下autoCheckUpgrade方法

有这个方法么大哥？ 这不是init方法的参数么？而且默认就是true。 不调用update方法，会提示更新中，已是最新版本（并不是最新版 build号 版本号都是低于后台上传的版本）；手动调用update，提示更新中，然后就没反应了

**Comment by crazecoder** [comment]
> > 还存在这个问题吗？试下autoCheckUpgrade方法
> 
> 有这个方法么大哥？ 这不是init方法的参数么？而且默认就是true。 不调用update方法，会提示更新中，已是最新版本（并不是最新版 build号 版本号都是低于后台上传的版本）；手动调用update，提示更新中，然后就没反应了

autoCheckUpgrade的确是init参数，手动调用update需要设置FlutterBugly.onCheckUpgrade.listen

**Comment by GoogleJ** [comment]
问题太多了。。。debug模式下提示已经是最新版（卸载、重新安装都不行，并不是最新版）。打成release 安装，可以弹出更新对话框。点击立即更新。对话框没了，无法更新，再次打开提示继续下载，再点击，又没了。等了很久也没动静。

打算手动调用getUpdateInfo，手动download。如果不是后台无法提供接口，是不考虑用bugly也不会用这个plugin的。

**Comment by crazecoder** [comment]
不太清楚你是用的什么模式，我自己的线上项目用的是这个插件，没什么问题
