### ISSUE TITLE
iOS ，  No podspec exists 

### ISSUE THREAD

**Issue by bilx** [crazecoder/flutter_bugly#115]
![image](https://user-images.githubusercontent.com/22422723/120420666-5ea0b300-c397-11eb-90e8-ed7c1b94a945.png)

作者大大，我使用的版本是 0.3.1， 在运行iOS的时候出现这个错误，请问有可能是什么原因？

**Comment by crazecoder** [comment]
pod install --repo-update 试试这个命令
