### ISSUE TITLE
手动检查更新bug

### ISSUE THREAD

**Issue by hwh97** [crazecoder/flutter_bugly#116]
FlutterBugly.checkUpgrade(isManual: false, isSilence: true);

设置了isSilence还是会弹出 “你已经是最新版了”的提示

**Comment by Herryjoeson** [comment]
checkUpgrade源码没有result.success，一直等待返回

**Comment by gj2569355373** [comment]
一样的问题，不知道如何才能去掉“你已经是最新版了”的提示

**Comment by crazecoder** [comment]
0.3.3测试没有复现这个问题
