### ISSUE TITLE
更新不会自动弹窗，锁屏再解锁之后有更新提示框

### ISSUE THREAD

**Issue by ludy520** [crazecoder/flutter_bugly#117]
flutter：2.2.1版本，
flutter_bugly:support

日志打印获取到了新版本信息，但是不会弹窗，锁屏后再解锁，更新提示框出现？怎么样可以不锁屏也弹窗？

**Comment by crazecoder** [comment]
手动调用check方法或者使用flutter在FlutterBugly.onCheckUpgrade.listen内showdialog，bugly原生的弹窗机制应该是在onresume里的，flutter这边逻辑可能会导致onresume时未初始化完成，所以不弹窗
