### ISSUE TITLE
“你已经是最新版了”要怎么去掉

### ISSUE THREAD

**Issue by gj2569355373** [crazecoder/flutter_bugly#120]
每次都会提醒，参数都有试了
没作用

**Comment by crazecoder** [comment]
这边debug/release都没有复现，你使用的版本是多少

**Comment by luokunman** [comment]
> 这边debug/release都没有复现，你使用的版本是多少

我用最新版本的话  也会，   就是初始化的时候会提醒。

**Comment by lurongshuang** [comment]
FlutterBugly.checkUpgrade(isManual: false, isSilence: true);
会 提示：“你已经是最新版了”
