### ISSUE TITLE
 No podspec found for `flutter_bugly_play` in `.symlinks/plugins/flutter_bugly_play/ios`

### ISSUE THREAD

**Issue by zhuzeyi2008** [crazecoder/flutter_bugly#125]
No podspec found for `flutter_bugly_play` in `.symlinks/plugins/flutter_bugly_play/ios`

**Comment by sy5075391** [comment]
> flutter clean 看看

https://github.com/crazecoder/flutter_bugly/issues/151   是否能更新个版本呢
