### ISSUE TITLE
与你的open_file冲突，咋整

### ISSUE THREAD

**Issue by liguande** [crazecoder/flutter_bugly#13]
Execution failed for task ':app:processDebugManifest'.                  
> Manifest merger failed : Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from [:flutter_bugly] AndroidManifest.xml:18:17-55
        is also present at [:open_file] AndroidManifest.xml:20:17-50 value=(@xml/filepaths).

**Comment by crazecoder** [comment]
open_file的readme有解决的方法，而且这个提示也很明显了
