### ISSUE TITLE
全量升级不提示？

### ISSUE THREAD

**Issue by evansherry** [crazecoder/flutter_bugly#131]
1. 在main中注册bugly,升级完全不提示？
`void main() => FlutterBugly.postCatchedException(() async {
      runApp(MyApp());
        FlutterBugly.init(
    androidAppId: BUGLY_ANDROID_APP_ID,
    iOSAppId: BUGLY_IOS_APP_ID,
    initDelay: 1,
  );

  FlutterBugly.onCheckUpgrade.listen((_upgradeInfo) {
    print('_upgradeInfo: $_upgradeInfo');
  });
    });
`
同时，日志打印“你已放弃让SDK来处理策略”。
我发现设置Beta.upgradeListener后，onUpgrade方法没有调用。

2. 设置customUpgrade = false，升级则会提示。

**Comment by evansherry** [comment]
自动检查更新就跟摇奖样的，时有时无，还是得手动调

**Comment by crazecoder** [comment]
建议手动调用，自动检查是bugly内部加密封装的逻辑，不可控
