### ISSUE TITLE
上传升级包versionCode为1，上传flutter后获取的versionCode为1001，求解

### ISSUE THREAD

**Issue by starry-sky-a** [crazecoder/flutter_bugly#134]
上传升级包versionCode为1，上传flutter后获取的versionCode为1001，求解
![image](https://user-images.githubusercontent.com/95609181/144804410-44191f00-6e55-4c23-bae4-297f88368201.png)
![image](https://user-images.githubusercontent.com/95609181/144804513-03c69c34-f375-4847-99e9-0b7deadbf805.png)

**Comment by ljhang** [comment]
@starry-sky-a  https://github.com/fluttercommunity/plus_plugins/issues/1035
