### ISSUE TITLE
隐私权限问题

### ISSUE THREAD

**Issue by winnxiegang** [crazecoder/flutter_bugly#139]
目前隐私权限各个平台检测，初次安装（还没弹出用户同意获取隐私权限时），后台会默认获取 mac地址 或者其他的隐私权限吗？

**Comment by zhangjianguo1** [comment]
我也遇到了这个问题不知道是不是bugly导致的。

1.详细描述：您的应用在用户同意隐私政策前申请获取用户的（ANDROID ID）个人信息。 ­请参考《审核指南》第7.5相关审核要求：https://developer.huawei.com/consumer/cn/doc/50104 ­修改建议：请在用户同意隐私政策后再申请获取用户个人信息及权限。 ­相关法律及规定请参考《网络安全法》及《关于开展APP侵害用户权益专项整治工作的通知》 ­APP常见个人信息保护问题FAQ请参考： ­https://developer.huawei.com/consumer/cn/doc/FAQ-faq

**Comment by shenhuaxiyuan** [comment]
一样遇到了这个问题，也怀疑是bugly的问题，因为postCatchedException方法是写在main里面的。但是查看了这个方法的实现又好像不涉及什么，有点没有头绪

**Comment by songsongtao** [comment]
同上，没有手动初始化的方法，直接初始化获取了用户的隐私上不了架

**Comment by hzp1993** [comment]
放弃了 搞不定。试了很多方法

**Comment by yuanzhiying** [comment]
同问，APP有隐私政策的，必须在隐私政策之后初始化，FlutterBugly.postCatchedException如何放置？

**Comment by jhfkf** [comment]
解决了吗 被拒麻了....

**Comment by biglin** [comment]
同问一下如何解决

**Comment by wva37254626** [comment]
同问,如何解决合规问题,能出个文档介绍吗

**Comment by navyzhou926** [comment]
FlutterBugly.postCatchedException这个调用了没有关系，开始没有异常不会执行底层的方法。其它的FlutterBugly方法，如FlutterBugly.setUserId需要放到用户同意隐私政策之后就行了，我的可以正常上架了

**Comment by suyie001** [comment]
init 需要放到用户同意隐私政策之后吗

**Comment by wxc64970** [comment]
> init 需要放到用户同意隐私政策之后吗

同问？有解决的吗？
