### ISSUE TITLE
提供一个手动提交异常的接口

### ISSUE THREAD

**Issue by shingohu** [crazecoder/flutter_bugly#14]
有些插件会有异常,例如视频播放的,收集不到,又没有机器测试,能否把postCatchedException 接口单独提供一个出来

**Comment by crazecoder** [comment]
插件异常有很多种，postCatchedException会提交本项目所有dart的异常，即使是第三方插件

**Comment by shingohu** [comment]
我的问题,之前看没记录到,今天一看好多。不过还是建议提供一个上传异常信息的接口。有时候一些业务上的异常我希望也能上传上去

**Comment by shingohu** [comment]
而且我看了下,我用了视频播放器的插件,某些机器播放视频失败,但是没记录到异常

**Comment by crazecoder** [comment]
播放器引擎内部异常，除非是播放器抛出给外层java或者dart，否则不会上报，另如果想要捕捉某个异常，可以主动throw

**Comment by shingohu** [comment]
是啊,可以提供一个接口主动提交异常信息

**Comment by crazecoder** [comment]
https://github.com/crazecoder/flutter_stack_trace/blob/master/example/lib/main.dart
