### ISSUE TITLE
试了各种办法，后台都没有正常捕获到异常，而且也没有装机量，启动次数的统计

### ISSUE THREAD

**Issue by tiansuo** [crazecoder/flutter_bugly#141]
我参考了86的启动方式，实际代码如下

![image](https://user-images.githubusercontent.com/17905624/147625360-7426f7e4-21a4-4801-8e52-881eca12c59d.png)

初始化成功了，但是后台就是无论如何获取不到错误信息和装机启动信息

![image](https://user-images.githubusercontent.com/17905624/147625416-43dc0f05-65b1-403f-b867-ca400aa46345.png)

写一个类型错误的页面，触发错误

![image](https://user-images.githubusercontent.com/17905624/147625471-76d717b3-3050-4f57-a481-ce4c0949db67.png)

后台啥都没有

![image](https://user-images.githubusercontent.com/17905624/147625493-e7001c8d-28c6-437c-910b-8944793731be.png)

![image](https://user-images.githubusercontent.com/17905624/147625506-85e76ecf-ee56-419a-8bba-af647566ab3a.png)

异常和运营统计通通没有，是还需要做其他的设置，还是需要什么啊，都一周了，bugly上提交反馈也没人回复，哎

**Comment by loongwind** [comment]
同样的问题，请问解决了么

**Comment by littleZzz** [comment]
我也遇到了相同的问题 最终各种尝试貌似是解决了 分享一下我的处理
1.将userId这些配置上 然后就能看到有运营统计信息了  
FlutterBugly.setUserId
FlutterBugly.putUserData
FlutterBugly.setAppChannel
FlutterBugly.setUserTag
2.进行第一步操作以后可以看到运营统计有数据了 但是还是没有bug日志信息   分析代码运行日志后  发现报错一个SSL的网络问题  导致无法post上去bug日志信息  各种尝试以后发现是手机连接公司内网导致  然后切换到数据流量进行错误日志上报  就可以正常使用了（android和ios都可以）

**Comment by pengfeigao** [comment]
各位去这儿看看吧？
<img width="201" alt="image" src="https://github.com/crazecoder/flutter_bugly/assets/9261499/ec4fb175-13e5-4ffc-b060-fbfa3a70c17a">

**Comment by junixapp** [comment]
同样的问题，提示初始化成功，手动制造异常，无任何数据异常/错误/崩溃统计，都没有数据

**Comment by crazecoder** [comment]
代码设置debugUpload: true，然后至错误分析tab下查看，部分情况下会有一定延迟
