### ISSUE TITLE
获取更新信息后，信息不全，title，version没有了？

### ISSUE THREAD

**Issue by ludy520** [crazecoder/flutter_bugly#143]
![image](https://user-images.githubusercontent.com/4113005/147816586-2c46800e-2b0b-4102-82dd-ca26c913dea1.png)

**Comment by zmm2tysu** [comment]
同上，onCheckUpgrade监听中获取不到title跟feature， 但是控制台CrashReport打印了这两个参数值的

**Comment by ludy520** [comment]
![image](https://user-images.githubusercontent.com/4113005/148349140-066c1dd2-40b5-4205-a535-29b13eb4ae89.png)
这里转换有问题

**Comment by hxywuya** [comment]
我今天刚升级到 0.4.3 也发现了同样的问题，话说现在最高哪个版本没这个问题

**Comment by hxywuya** [comment]
经过一系列测试，0.3.4版本是没有问题，之后的每一个版本我都试了 都存在此问题 @crazecoder @AlexV525

**Comment by AlexV525** [comment]
可否帮忙通过 `git bisect` 定位到哪个位置出了问题？手上暂时没有 bugly 项目。

**Comment by hxywuya** [comment]
我晚点可以试一下，不过我还没搞过这种的，我可能还得学习下
