### ISSUE TITLE
Didn't find class "com.tencent.tinker.lib.util.TinkerLog

### ISSUE THREAD

**Issue by mitty1987** [crazecoder/flutter_bugly#15]
明明没用到热更新，为什么报这个错呢
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.lib.util.TinkerLog$TinkerLogImp" on path: DexPathList[[zip file "/data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/base.apk"],nativeLibraryDirectories=[/data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/lib/arm, /data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
I/zygote  (12929):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote  (12929):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote  (12929):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote  (12929):   at void com.tencent.bugly.beta.tinker.TinkerManager.setPatchRestartOnScreenOff(boolean) (BUGLY:79)
I/zygote  (12929):   at void com.tencent.bugly.beta.Beta.init(android.content.Context, boolean) (BUGLY:479)
I/zygote  (12929):   at void com.tencent.bugly.beta.Beta.init(android.content.Context, boolean, com.tencent.bugly.BuglyStrategy) (BUGLY:594)
I/zygote  (12929):   at void com.tencent.bugly.b.a(android.content.Context, java.lang.String, boolean, com.tencent.bugly.BuglyStrategy) (BUGLY:170)
I/zygote  (12929):   at void com.tencent.bugly.Bugly.init(android.content.Context, java.lang.String, boolean, com.tencent.bugly.BuglyStrategy) (BUGLY:63)
I/zygote  (12929):   at void com.tencent.bugly.Bugly.init(android.content.Context, java.lang.String, boolean) (BUGLY:37)
I/zygote  (12929):   at void com.crazecoder.flutterbugly.FlutterBuglyPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBuglyPlugin.java:80)
I/zygote  (12929):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote  (12929):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote  (12929):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote  (12929):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote  (12929):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote  (12929):   at void android.os.Looper.loop() (Looper.java:169)
I/zygote  (12929):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7022)
I/zygote  (12929):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (12929):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:515)
I/zygote  (12929):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:837)

**Comment by crazecoder** [comment]
```
[/data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/lib/arm, /data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```
应该是这里报错

**Comment by mitty1987** [comment]
> ```
> [/data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/lib/arm, /data/app/com.ifavorite.pet.petlittle-l9V9fh7FQ7V87N7UGRFVVw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> ```
> 
> 应该是这里报错

不太理解，我已经加了abiFilters 'armeabi-v7a'，编译参数用的--target-platform android-arm

**Comment by Ucoon** [comment]
请问这个问题解决了吗。打包出来app闪退，也是报这个错

**Comment by ThreeZ3** [comment]
可以尝试如下：
implementation 'com.tencent.tinker:tinker-android-lib:1.9.9'
