### ISSUE TITLE
android postException 没有传递crash_data数据

### ISSUE THREAD

**Issue by OnesMobile** [crazecoder/flutter_bugly#163]
private void postException(MethodCall call) {
        String message = "";
        String detail = null;
        if (call.hasArgument("crash_message")) {
            message = call.argument("crash_message");
        }
        if (call.hasArgument("crash_detail")) {
            detail = call.argument("crash_detail");
        }
        if (TextUtils.isEmpty(detail)) return;
        CrashReport.postException(8, "Flutter Exception", message, detail, null);

    }

**Comment by crazecoder** [comment]
不太明白你的意思，官方文档也没查到crash_data字段相关
