### ISSUE TITLE
运营统计无数据

### ISSUE THREAD

**Issue by Huuuuuub** [crazecoder/flutter_bugly#164]
接入插件后，运行APP到真机，错误倒是可以抓到，但是发现没有运营数据。翻看之前的ISSUE，有人提出过这这样的问题，有个回复说设置下 ： FlutterBugly.setAppChannel('appstore');  FlutterBugly.setUserId('xxx');
        FlutterBugly.setUserTag(111);
        FlutterBugly.putUserData(key: 'User_Phone', value: '33333');这几个，但是我设置完后，发现Android倒是出现了使用人数，但是安装人数是空，iOS的运营数据都是空，请问此问题如何处理？

**Comment by crazecoder** [comment]
官方运营统计感觉一直有问题，你可以加他们官方群问问

**Comment by Huuuuuub** [comment]
> 官方运营统计感觉一直有问题，你可以加他们官方群问问

嗯，估计是了
