### ISSUE TITLE
MissingPluginException(No implementation found for method postCatchedException on channel crazecoder/flutter_bugly)

### ISSUE THREAD

**Issue by aniealss** [crazecoder/flutter_bugly#167]
是否可以将插件的 gradle 版本升级到 8.x

**Comment by crazecoder** [comment]
支持

**Comment by aniealss** [comment]
请问下 MissingPluginException 这个问题可以怎么解决？

**Comment by crazecoder** [comment]
flutter clean后再试试

**Comment by aniealss** [comment]
试过的，我这边其他自己封住的插件，是通过将插件的 gradle 版本升级到 8.x 解决的

**Comment by crazecoder** [comment]
你用的gradle版本是多少？我试下

**Comment by aniealss** [comment]
8.1.0

**Comment by crazecoder** [comment]
我clean之后试了810和873，都没问题，如果你可以在example里有复现的方法，请告知我

**Comment by aniealss** [comment]
这个问题，是线上版本在 firebase 上报的错误。我也没复现

我这边其他有问题的插件，之前用的也都是7.x，之后改为8.x 后，线上就没有报 MissingPluginException

**Comment by crazecoder** [comment]
已升级，你可以试试
