### ISSUE TITLE
BuglyLog 支持？

### ISSUE THREAD

**Issue by aniealss** [crazecoder/flutter_bugly#168]
能否可以封装一下
BuglyLog.v(tag, log)
BuglyLog.d(tag, log)
BuglyLog.i(tag, log)
BuglyLog.w(tag, log)
BuglyLog.e(tag, log)

**Comment by crazecoder** [comment]
一般来说debugprint就够了，而且flutter很多log插件，这个插件里除了ios的一个nslog，也没有其他log，所以不必执着于BuglyLog

**Comment by aniealss** [comment]
好的，谢谢。主要是想在发生异常时，将一些自定义日志，通过 BuglyLog 一起上传

**Comment by crazecoder** [comment]
你是为了上传log文件是吧？那确实是可以加一下
