### ISSUE TITLE
iOS崩溃，插件版本需要更新

### ISSUE THREAD

**Issue by Langthron** [crazecoder/flutter_bugly#169]
@crazecoder 我使用1.0.7版本在iOS上发生了崩溃，发现你在最新的[这个commit](https://github.com/crazecoder/flutter_bugly/commit/bc02aa60b316cb157fada1945179d87bf4d8164c)已经修复了，但是没有发布插件新版本~

**Comment by crazecoder** [comment]
最新版是1.0.7+1发自我的 iPhone在 2024年12月30日，14:27，langthron ***@***.***> 写道：﻿
@crazecoder 我使用1.0.7版本在iOS上发生了崩溃，发现你在最新的这个commit已经修复了，但是没有发布插件新版本~

**Comment by Langthron** [comment]
害，我的锅，没去pub那边看最新版本
