### ISSUE TITLE
 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/zhangruiyu/FlutterProjects/abc/ios/Pods/Bugly/Bugly.framework)

### ISSUE THREAD

**Issue by zhangruiyu** [crazecoder/flutter_bugly#17]
'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/zhangruiyu/FlutterProjects/abc/ios/Pods/Bugly/Bugly.framework)

**Comment by crazecoder** [comment]
3b12cf3d1929dcac38fa417c2fc9144950e7475c
