### ISSUE TITLE
安卓集成成功后后，bugly运营统计内没有数据

### ISSUE THREAD

**Issue by 370966584** [crazecoder/flutter_bugly#18]

**Comment by crazecoder** [comment]
确定id是否正确，会有延迟的情况

**Comment by 370966584** [comment]
> 确定id是否正确，会有延迟的情况

appid 肯定对的，  这都一两天了  还是没有数据
![image](https://user-images.githubusercontent.com/26058251/55928566-c6419480-5c4b-11e9-8e29-fa408a2635b8.png)

**Comment by 370966584** [comment]
> 确定id是否正确，会有延迟的情况
刚才有故意测试了下崩溃，错误分析里面是有数据的

**Comment by qq125183592** [comment]
错误分析是有的，但是运营统计里没有

**Comment by Seifon** [comment]
我也是，没有运营统计数据

**Comment by jiabin87428** [comment]
为啥关了，我也是，安卓没有运营统计数据，iOS有
