### ISSUE TITLE
最新版本还是androidX不兼容，编译失败

### ISSUE THREAD

**Issue by baoxiehao** [crazecoder/flutter_bugly#22]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preReleaseBuild'.
> Android dependency 'androidx.fragment:fragment' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s

**Comment by crazecoder** [comment]
```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.fragment'
                    && !details.requested.name.contains('fragment') ) {
                details.useVersion "1.0.0"
            }
        }
    }
}
```
/android/build.gradle

**Comment by baoxiehao** [comment]
试了还是不行

**Comment by baoxiehao** [comment]
今天升级到最新stable 1.5 flutter版本就可以编译过了...
