### ISSUE TITLE
不支持armeab、armeabi-v7a吗

### ISSUE THREAD

**Issue by damo2** [crazecoder/flutter_bugly#23]
flutter_bugly:
      git:
        url: git://github.com/crazecoder/flutter_bugly.git
        ref: dev

ndk {
            //设置支持的SO库架构
            abiFilters  'armeabi-v7a'//'armeabi','armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
}

直接运行报错

Process: com.leimo.erp, PID: 28735
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.damo.demo-y8PSY4tok7qoAAb2V4130w==/base.apk"],nativeLibraryDirectories=[/data/app/com.damo.demo-y8PSY4tok7qoAAb2V4130w==/lib/arm, /data/app/com.damo.demo-y8PSY4tok7qoAAb2V4130w==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libflutter.so"

通过命令打包没问题
flutter build apk --release --target-platform android-arm

**Comment by jp1017** [comment]
同样遇到问题

**Comment by epenli** [comment]
同问 @crazecoder

**Comment by ikimiler** [comment]
同样的问题

**Comment by crazecoder** [comment]
flutter/flutter#29710
