### ISSUE TITLE
最新版编译打包失败

### ISSUE THREAD

**Issue by caiorngcai** [crazecoder/flutter_bugly#24]
依赖的.so
 ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi-v7a'//, 'arm64-v8a', 'x86', 'x86_64'
        }
报以下错误：

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/arm64-v8a/libBugly.so'

**Comment by damo2** [comment]
我就是直接运行不行，用命令能打包成功。
用命令 flutter build apk 能打包试试。如果能行只在release 设置支持的架构。
buildTypes {
        release {
            signingConfig signingConfigs.release
            ndk {
                abiFilters  'armeabi-v7a'
            }
        }
    }

**Comment by crazecoder** [comment]
```gradle
buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            ndk {
                //设置支持的SO库架构
                abiFilters 'armeabi-v7a', 'arm64-v8a'//,'x86',  'x86_64'
            }
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            ndk {
                //设置支持的SO库架构
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            }
        }
    }
```
