### ISSUE TITLE
无法获取到更新数据

### ISSUE THREAD

**Issue by qq125183592** [crazecoder/flutter_bugly#29]
新建一个version: 1.0.1+2 传到bugly后台，然后本地装1.0.0+1

FlutterBugly.getUpgradeInfo().then((UpgradeInfo info) {});

这个info打印一直是null，从未获取到新版信息，都一个小时也没反应，反复打开都是null。奇怪的是bugly后台已下发数量会增加，求作者解答～

**Comment by crazecoder** [comment]
版本多少

**Comment by qq125183592** [comment]
> 版本多少

flutter_bugly: ^0.2.0

**Comment by crazecoder** [comment]
check或者auto了吗？

**Comment by qq125183592** [comment]
> check或者auto了吗？

没有，看示例是点击后执行FlutterBugly.getUpgradeInfo()，我想进页面自动FlutterBugly.getUpgradeInfo()，没有任何操作想触发，是否不能这样做？

**Comment by crazecoder** [comment]
因为现在这个方法走的是网络监听，需要先调用一次更新策略拉取，再去get才有数据，建议设置auto或者在check后再get

**Comment by qq125183592** [comment]
> 因为现在这个方法走的是网络监听，需要先调用一次更新策略拉取，再去get才有数据，建议设置auto或者在check后再get

好的，多谢，我试试

**Comment by crazecoder** [comment]
我在优化一下获取机制吧

**Comment by qq125183592** [comment]
`

      await FlutterBugly.checkUpgrade(isManual: false, isSilence: false);
      UpgradeInfo info = await FlutterBugly.getUpgradeInfo();

      Fluttertoast.showToast(
        msg: "获取地址"+info.toString(),
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
        timeInSecForIos: 1,
      );
`

autoCheckUpgrade 我看是默认的 也还是设置为true了，然后上面代码继续check再get ，弹出的仍然是null，后台已下发数量有增加1，反复再打开还是null，不知道什么原因

**Comment by qq125183592** [comment]
> 我在优化一下获取机制吧

好的，期待更新

**Comment by crazecoder** [comment]
已更新，试下0.2.0+1

**Comment by qq125183592** [comment]
> 已更新，试下0.2.0+1

更新后可以获取了，多谢
