### ISSUE TITLE
怎样关闭debug模式？

### ISSUE THREAD

**Issue by Seifon** [crazecoder/flutter_bugly#32]
/dalvikvm(16492): Unable to resolve superclass of Lcom/tencent/bugly/beta/tinker/TinkerApplicationLike; (4601)
W/dalvikvm(16492): Link of class 'Lcom/tencent/bugly/beta/tinker/TinkerApplicationLike;' failed
I/dalvikvm(16492): Could not find method com.tencent.bugly.beta.tinker.TinkerApplicationLike.getTinkerPatchApplicationLike, referenced from method com.tencent.bugly.beta.Beta.installTinker
W/dalvikvm(16492): VFY: unable to resolve static method 34244: Lcom/tencent/bugly/beta/tinker/TinkerApplicationLike;.getTinkerPatchApplicationLike ()Lcom/tencent/tinker/entry/ApplicationLike;
D/dalvikvm(16492): VFY: replacing opcode 0x71 at 0x0003
W/CrashReport(16492): Bugly debug模式开启，请在发布时把isDebug关闭。 -- Running in debug model for 'isDebug' is enabled. Please disable it when you release.
E/CrashReport(16492): --------------------------------------------------------------------------------------------
W/CrashReport(16492): Bugly debug模式将有以下行为特性 -- The following list shows the behaviour of debug model: 
W/CrashReport(16492): [1] 输出详细的Bugly SDK的Log -- More detailed log of Bugly SDK will be output to logcat;
W/CrashReport(16492): [2] 每一条Crash都会被立即上报 -- Every crash caught by Bugly will be uploaded immediately.
W/CrashReport(16492): [3] 自定义日志将会在Logcat中输出 -- Custom log will be output to logcat.
E/CrashReport(16492): --------------------------------------------------------------------------------------------
I/CrashReportInfo(16492): [init] Open debug mode of Bugly.
I/CrashReport(16492): [init] Bugly version: v2.6.5
I/CrashReport(16492):  crash report start initializing...
I/CrashReportInfo(16492): [init] Bugly start initializing...
I/CrashReport(16492): [init] Bugly complete version: v2.6.5(1.3.7)

**Comment by crazecoder** [comment]
release模式自动关闭

**Comment by Seifon** [comment]
我在bugly上传了一个版本，软件里面加了你写的更新检查。可是没有弹出提示框

**Comment by crazecoder** [comment]
Androidx需要自己写弹窗逻辑

**Comment by Seifon** [comment]
> Androidx需要自己写弹窗逻辑

在弹窗前，我加了日志打印，可是没有打印我写的日志。

只有这几行程序日志：

```
I/View    (26138): Touch down dispatch to io.flutter.view.FlutterView{4225f0a8 VFE..... .F...... 0,0-1280,737}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=636.50275, y[0]=372.53433, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1643340976, downTime=1643340976, deviceId=3, source=0x1002 }
I/View    (26138): Touch up dispatch to io.flutter.view.FlutterView{4225f0a8 VFE..... .F...... 0,0-1280,737}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=636.50275, y[0]=372.53433, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1643341130, downTime=1643340976, deviceId=3, source=0x1002 }
V/Provider/Settings(26138):  from settings cache , name = sound_effects_enabled , value = 0

```

**Comment by Seifon** [comment]
> Androidx需要自己写弹窗逻辑

我打印了日志，取不到版本信息

```
I/flutter (26138): 检查新版本...
I/flutter (26138): 检查新版本... info:【】
```

**Comment by Seifon** [comment]
```
I/View    (27047): Touch down dispatch to io.flutter.view.FlutterView{41f14e60 VFE..... .F...... 0,0-1280,737}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=653.48944, y[0]=386.51688, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1644765481, downTime=1644765481, deviceId=3, source=0x1002 }
I/View    (27047): Touch up dispatch to io.flutter.view.FlutterView{41f14e60 VFE..... .F...... 0,0-1280,737}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=653.48944, y[0]=386.51688, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1644765616, downTime=1644765481, deviceId=3, source=0x1002 }
V/Provider/Settings(27047):  from settings cache , name = sound_effects_enabled , value = 0

```
