### ISSUE TITLE
这个错误有影响吗？

### ISSUE THREAD

**Issue by Seifon** [crazecoder/flutter_bugly#33]
D/CrashReport(18375): [UploadManager] Local network consume: 61 KB
D/CrashReport(18375): [Database] deleted t_lr data 1
D/CrashReport(18375): [Database] insert t_lr success.
D/CrashReport(18375): [UploadManager] Network total consume: 62 KB
I/CrashReport(18375): upload succ:[804] [sended 800] [recevied 129]
I/CrashReport(18375): 你已放弃让SDK来处理策略
I/CrashReport(18375): betaStrategy is null
I/CrashReport(18375): 用户自定义activity，创建task失败 [strategy:null]

**Comment by crazecoder** [comment]
没有，原生也会有这个错
