### ISSUE TITLE
调用checkUpgrade后无任何反应

### ISSUE THREAD

**Issue by weiwei00200** [crazecoder/flutter_bugly#35]
1.FlutterBugly.init(androidAppId: "xxxx");
2.FlutterBugly.checkUpgrade(isManual: true,isSilence: false)

我一共使用了这两个，app入口处先调用了init方法了，然后在一个按钮那里点击调用了checkUpgrade，检测的toast弹出后就没任何反应了。我有放了个versionName 和 versionCode比较高的版本到后台的，不会弹出那个已经是最新版的toast了，应该是能证明检测到了新版本的

**Comment by crazecoder** [comment]
Androidx需自行处理更新界面问题
