### ISSUE TITLE
ios端，日志有点奇怪

### ISSUE THREAD

**Issue by Seifon** [crazecoder/flutter_bugly#37]
ios端的异常日志排版有点乱，不像安卓那样清晰，希望能够优化一下

https://cdn.sinaimg.cn.52ecy.cn/large/005BYqpgly1g3en30dngvj311q0u04by.jpg

**Comment by crazecoder** [comment]
bugly机制问题，暂时没法解决，如有研究过这个问题的，可以fork修改push

**Comment by crazecoder** [comment]
#38
