### ISSUE TITLE
flutter_bugly 和open file好像有一些冲突

### ISSUE THREAD

**Issue by zakiso** [crazecoder/flutter_bugly#46]
![image](https://user-images.githubusercontent.com/5389326/59113695-1f8e2180-8978-11e9-830c-2d23854285e3.png)

![image](https://user-images.githubusercontent.com/5389326/59113674-11d89c00-8978-11e9-8b50-2500f9078d1e.png)

是否应该把flutter bugly的Android manifest文件中的meta-data删除？
```
 <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
```

**Comment by crazecoder** [comment]
加入tools:replace="android:resource"

**Comment by zakiso** [comment]
不行，加入这个报错， 需要项目本身有用android:resource 才能加。否则添加会报错，找不到replace什么来着。 你bugly中也并没有提供provider_paths.xml这个文件,应该删除掉吧。

**Comment by crazecoder** [comment]
报错信息呢

**Comment by zakiso** [comment]
项目同时使用你的flutter_bugly和open_file会出现如下的错误，
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/5389326/60326528-69d55200-99bc-11e9-9d55-839c293974bd.png">

如果添加上tools:replace="android:resource"报错如下：
<img width="962" alt="image" src="https://user-images.githubusercontent.com/5389326/60326696-bc167300-99bc-11e9-9259-22fcadbae06d.png">

**Comment by crazecoder** [comment]
其实open_file的readme写的很清楚
需要在manifest标签增加xmlns:tools="http://schemas.android.com/tools"
