### ISSUE TITLE
既然开源麻烦维护好，一堆的bug

### ISSUE THREAD

**Issue by ikimiler** [crazecoder/flutter_bugly#48]
await FlutterBugly.init(
      autoCheckUpgrade: false,
      autoDownloadOnWifi: false,
      androidAppId: "c4888681a0",
      // iOSAppId: "c4888681a0",
    );
    await FlutterBugly.checkUpgrade(isManual: false, isSilence: true);
    await FlutterBugly.checkUpgrade(isManual: false, isSilence: true);
    await FlutterBugly.checkUpgrade(isManual: false, isSilence: true);
    var info = await FlutterBugly.getUpgradeInfo();
很大几率info为空，做了延迟处理还是不行，是官方的问题还是你的问题？

Rejecting re-init on previously-failed class java.lang.Class<com.tencent.bugly.beta.tinker.TinkerApplicationLike>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/entry/DefaultApplicationLike;

各种错误，麻烦好好维护它

**Comment by crazecoder** [comment]
首先checkUpgrade是使用网络拉取数据，本地如果没有升级策略，在未完成网络拉取策略的时候去getUpgradeInfo必定会是null，后期会改成checkUpgrade直接返回网络策略。
另外报错，你即使用原生按照文档去集成也会出现，原因请加官方群问bugly官方

**Comment by crazecoder** [comment]
## 0.2.3
* 优化checkUpgrade方法，等待网络请求更新策略完成后再返回UpgradeInfo（注意点见方法注释）
* 升级com.tencent.bugly:crashreport_upgrade:1.4.1
