### ISSUE TITLE
三星平板加入这句闪退

### ISSUE THREAD

**Issue by iyzwei4666** [crazecoder/flutter_bugly#49]
ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi-v7a'//, 'arm64-v8a', 'x86', 'x86_64'
        }

Samsung Galaxy Tab S2
型号  sm-t713

Key features:
System: Android 7.0
Processor: Octa Core / Quad 1.８ GHz & Quad 1.４ GHz
Memory: Internal: 32 GB / RAM: 3 GB / Slot type: microSD / Max. slot capacity: 128 GB

**Comment by crazecoder** [comment]
首先确定cpu架构，然后尝试用release命令打包后安装试试
