### ISSUE TITLE
集成flutter_bugly后执行build apk，控制台报错如下，请问是哪里需要配置吗？

### ISSUE THREAD

**Issue by bianxiang** [crazecoder/flutter_bugly#51]
![image](https://user-images.githubusercontent.com/16380379/62018918-4980f900-b1ef-11e9-89c9-485a4f224e1e.png)

**Comment by crazecoder** [comment]
报错里有提示在manifest里加tools:replace="android:authorities"和android:resource，记得在最外层加上xmlns:tools="http://schemas.android.com/tools"

**Comment by bianxiang** [comment]
已解决，谢谢~~

**Comment by bianxiang** [comment]
一般来说suggestion的改动可以不改，请问这里为什么一定要改动，增加那几行的目的是什么？我主要做iOS的，对android方面不是很精通

**Comment by crazecoder** [comment]
```
flutter build apk --release --target-platform android-arm
```
打包时需要加入cpu架构适配

**Comment by bianxiang** [comment]
flutter1.9.1执行flutter run  --release --target-platform android-arm报错如下，请问怎么解决？
![image](https://user-images.githubusercontent.com/16380379/65825796-d149b900-e2ad-11e9-9147-e0db07aa7777.png)

**Comment by bianxiang** [comment]
之前是不报错的，如果不加后面的，打出来的包是闪退的

**Comment by CocoaZX** [comment]
加了
![image](https://user-images.githubusercontent.com/28552051/85942700-80124700-b95d-11ea-9961-2c8a64ae9c42.png)

**Comment by CocoaZX** [comment]
你的filepath也没用，为什么要加呢
