### ISSUE TITLE
真机无法收到更新推送

### ISSUE THREAD

**Issue by lawlietwind** [crazecoder/flutter_bugly#56]
你好，我使用了您的flutter_bugly，感觉挺不错的，不过遇到一个问题，虚拟机可以收到更新，根据教程中配合armeabi-v7a可以打出32位64位通用包，真机安装后却不能收到更新通知，这个不知怎么解决。更新的高版本也是配合armeabi-v7a打出的32位64位通用包，上传上去的。

**Comment by crazecoder** [comment]
大概情况
1、9.0以上适配，插件内已适配，但不排除和其他插件共用时冲突导致无效的情况
2、新版本flutter默认新建项目只在debug目录下的manifest里配置了网络权限，release下自行添加
3、bugly下发策略延迟
4、使用check方法调用
5、[官方解答](https://github.com/BuglyDevTeam/Bugly-Android-Demo/wiki/%E9%85%8D%E7%BD%AE%E4%BA%86%E5%8D%87%E7%BA%A7%E5%8C%85%EF%BC%8C%E4%BD%86%E6%98%AF%E4%B8%80%E7%9B%B4%E4%B8%8D%E5%BC%B9%E5%8D%87%E7%BA%A7%E6%8F%90%E7%A4%BA%E6%A1%86)

**Comment by eagle-1949** [comment]
这个你在example写个完整的demo啊，现在我的有提示，但是点击更新没有反应，下载apk，建议使用dio和open_file插件，这里为啥不写完整呢。

**Comment by lawlietwind** [comment]
确实是bugly下发策略延迟，不过虚拟机收到更新的速度比真机快好几天，目前找不到原因
