### ISSUE TITLE
flutter_downloader 插件配置文件冲突

### ISSUE THREAD

**Issue by lovachen** [crazecoder/flutter_bugly#59]

**Comment by crazecoder** [comment]
有log吗

**Comment by lovachen** [comment]
install_plugin 的AndroidManifest.xml 的配置 如下
<provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/> 
        </provider>

flutter_bugly 需要添加如下配置 ，二配置的结果导致install不可用，下载会报错
<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"
                tools:replace="android:resource" />
        </provider> 

按照官网的配置说明：如果你使用的第三方库也配置了同样的FileProvider, 可以通过继承FileProvider类来解决合并冲突的问题，示例如下：

<provider
    android:name=".utils.BuglyFileProvider"
    android:authorities="${applicationId}.fileProvider"
    android:exported="false"
    android:grantUriPermissions="true"
    tools:replace="name,authorities,exported,grantUriPermissions">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths"
        tools:replace="name,resource"/>
</provider>
并不起作用

**Comment by crazecoder** [comment]
我看了install_plugin，并没有下载方法
你可以发一下报错log

**Comment by lovachen** [comment]
不好意思，搞错了是 flutter_downloader 这个插件。

**Comment by lovachen** [comment]
我觉得可以弄一个单独不含有更新的插件，只包含日志上报，这样就不会和其它下载插件冲突了。

**Comment by crazecoder** [comment]
我尝试在example里集成了flutter_downloader，没有问题，你可以把报错日志发出来，可能是权限或者其他问题

**Comment by zxy12666** [comment]
我也遇到了这样的问题
![image](https://user-images.githubusercontent.com/23500521/66795974-cd1dcc80-ef38-11e9-83f6-fbab3cf55664.png)

**Comment by zxy12666** [comment]
> 我尝试在example里集成了flutter_downloader，没有问题，你可以把报错日志发出来，可能是权限或者其他问题

我也遇到了这样的问题
![image](https://user-images.githubusercontent.com/23500521/66797195-a1044a80-ef3c-11e9-95b9-38e715618f62.png)

**Comment by lovachen** [comment]
> 我尝试在example里集成了flutter_downloader，没有问题，你可以把报错日志发出来，可能是权限或者其他问题

是吗，我是下载的时候出现了错误。我再检查检查吧

**Comment by lovachen** [comment]
> > 我尝试在example里集成了flutter_downloader，没有问题，你可以把报错日志发出来，可能是权限或者其他问题
 是和 install_plugin 这个插件在安装的时候出现了错误
PlatformException(IllegalArgumentException, Couldn't find meta-data for provider with authority com.xxx.xxx.fileProvider.install, null)

**Comment by lovachen** [comment]
添加了如下的配置

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"

<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"
                tools:replace="android:resource" />
        </provider> 
```

**Comment by crazecoder** [comment]
https://github.com/fluttercommunity/flutter_downloader/issues/113
@lovachen
