### ISSUE TITLE
AndroidX的支持

### ISSUE THREAD

**Issue by hirohe** [crazecoder/flutter_bugly#6]
是否可以考虑迁移到支持AndroidX呢？

**Comment by hirohe** [comment]
我看到是GitHub版本的build.gradle和pub上的不一致，是说GitHub的版本有支持AndroidX吗？

**Comment by baoxiehao** [comment]
同问，@hirohe 你解决了？

.pub-cache/hosted/pub.flutter-io.cn/flutter_bugly-0.1.4/android/src/main/java/com/crazecoder/flutterbugly/FlutterBuglyPlugin.java:6: 错误: 找不到符号
import android.support.v4.app.ActivityCompat;
                             ^
  符号:   类 ActivityCompat
  位置: 程序包 android.support.v4.app
