### ISSUE TITLE
[Bugly]  Trapped uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull boolValue]: unrecognized selector sent to instance 0x1f3de3df0' 

### ISSUE THREAD

**Issue by android-pf** [crazecoder/flutter_bugly#60]
Android端毫无问题，IOS（iphone xr  12.1.2）运行起来之后闪退，错误如下：
[Bugly]  Trapped uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull boolValue]: unrecognized selector sent to instance 0x1f3de3df0' 
(
	0   CoreFoundation                      0x00000001c31a7f68 <redacted> + 256
	1   libobjc.A.dylib                     0x00000001c23a4284 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001c30bd0e0 <redacted> + 0
	3   CoreFoundation                      0x00000001c31ad9bc <redacted> + 1416
	4   CoreFoundation                      0x00000001c31af730 _CF_forwarding_prep_0 + 96
	5   Runner                              0x00000001010144c4 -[JPushPlugin setup:result:] + 480
	6   Runner                              0x0000000101013ac8 -[JPushPlugin handleMethodCall:result:] + 484
	7   Flutter                             0x00000001013a042c __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 116
	8   Flutter                             0x000000010133bdbc _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 680
	9   Flutter                             0x0000000101392654 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_31NS_9allocatorIS8_EEFvvEEclEv + 80
	10  Flutter                             0x00000001013499e8 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 132
	11  Flutter                             0x000000010134e09c _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
	12  CoreFoundation                      0x00000001c3136d18 <redacted> + 32
	13  CoreFoundation                      0x00000001c3136a44 <redacted> + 884
	14  CoreFoundation                      0x00000001c3136238 <redacted> + 252
	15  CoreFoundation                      0x00000001c3130ef8 <redacted> + 1832
	16  CoreFoundation                      0x00000001c31304b8 CFRunLoopRunSpecific + 452
	17  GraphicsServices                    0x00000001c53e3be8 GSEventRunModal + 104
	18  UIKitCore                           0x00000001f0e64048 UIApplicationMain + 216
	19  Runner                              0x0000000100f44e78 main + 76
	20  libdyld.dylib                       0x00000001c2be5050 <redacted> + 4
)
[Bugly] Fatal signal(6) raised.
[Bugly] Forward signal(6) to the previous handler: 0x0
Lost connection to device.

**Comment by crazecoder** [comment]
iOS模拟器我这边试了没问题，真机和打包因为条件限制，没法测试。。。
