### ISSUE TITLE
ios build 报错：'Bugly' uses the unencrypted 'http' protocol to transfer the Pod

### ISSUE THREAD

**Issue by tangbincheng** [crazecoder/flutter_bugly#65]
Error output from CocoaPods:
↳

    [!] 'Bugly' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library
    author to notify them of this security issue.

Error running pod install

**Comment by crazecoder** [comment]
官方问题
https://github.com/BuglyDevTeam/Bugly-iOS/issues/20
