### ISSUE TITLE
设置Crash回调

### ISSUE THREAD

**Issue by YanCorey** [crazecoder/flutter_bugly#66]
Android 端，能添加个setCrashHandleCallback不？
UserStrategy strategy = new UserStrategy(appContext);
strategy.setCrashHandleCallback(new CrashReport.CrashHandleCallback() {
    public Map<String, String> onCrashHandleStart(int crashType, String errorType, 
            String errorMessage, String errorStack) {
        LinkedHashMap<String, String> map = new LinkedHashMap<String, String>();
        map.put("Key", "Value");
        return map;
    }

    @Override
    public byte[] onCrashHandleStart2GetExtraDatas(int crashType, String errorType, 
            String errorMessage, String errorStack) {
        try {
            return "Extra data.".getBytes("UTF-8");
        } catch (Exception e) {
            return null;
        }
    }

});
CrashReport.initCrashReport(appContext, APPID, true, strategy);

**Comment by crazecoder** [comment]
自定义附件数据？
```dart
  ///上报自定义异常信息，data为文本附件
  ///Android 错误分析=>跟踪数据=>extraMessage.txt
  ///iOS 错误分析=>跟踪数据=>crash_attach.log
  static Future<Null> uploadException(
      {@required String message, @required String detail, Map data}) async {
    var map = {};
    map.putIfAbsent("crash_message", () => message);
    map.putIfAbsent("crash_detail", () => detail);
    if (data != null) map.putIfAbsent("crash_data", () => data);
    await _channel.invokeMethod('postCatchedException', map);
  }
```
这是不是你要的？

**Comment by YanCorey** [comment]
不知道哎 我看文档setCrashHandleCallback这个是初始化前调用的
问下uploadException能实现自定义crash的路径吗？
