### ISSUE TITLE
android端实时bug无法收集

### ISSUE THREAD

**Issue by YueMeng123** [crazecoder/flutter_bugly#68]
![image](https://user-images.githubusercontent.com/23230746/69854953-60327c00-12c5-11ea-88cb-6187758ea8c1.png)
我在build构件时手动报一个错误就能拿到，
![image](https://user-images.githubusercontent.com/23230746/69855027-86f0b280-12c5-11ea-9585-ba9f0192629b.png)
但是如果我在点击按钮里面这样做就无法收集到，

**Comment by crazecoder** [comment]
https://github.com/crazecoder/flutter_bugly/issues/62
最后有说明，所有的widget library catch的异常在debug模式下都只能偶尔回调onerror方法，这是flutter的问题，release下没问题

**Comment by YueMeng123** [comment]
好的，我去打个包测试一下
