### ISSUE TITLE
  flutter_bugly: 0.2.8 集成报错

### ISSUE THREAD

**Issue by DavidMGT** [crazecoder/flutter_bugly#69]
Manifest merger failed : Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from [:flutter_webview_plugin] AndroidManifest.xml:17:17-50
        is also present at [:flutter_bugly] AndroidManifest.xml:18:17-55 value=(@xml/provider_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

**Comment by crazecoder** [comment]
提示很明确了，AndroidManifest里的application加tools:replace="android:resource"，另外flutter_webview_plugin会去找自己拼接的fileprovider，而大部分库的命名都是fileProvider，建议fork最新flutter_webview_plugin找到拼接代码更改一下
