### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by weiwill** [crazecoder/flutter_bugly#7]
我这边执行pod install 的时候出现了标题上的错误
参考
https://github.com/jpush/jmessage-flutter-plugin/issues/3
在ios文件夹里面的flutter_bugly.podspec文件中中添加s.static_framework = true（在end前面一排即可！)
解决了这个问题

**Comment by shingohu** [comment]
@crazecoder 添加一下呗
