### ISSUE TITLE
app更新不显示

### ISSUE THREAD

**Issue by wyswill** [crazecoder/flutter_bugly#70]
![image](https://user-images.githubusercontent.com/26476386/70680547-9a434b00-1cd3-11ea-8fec-820da901b7a7.png)
![image](https://user-images.githubusercontent.com/26476386/70680568-ac24ee00-1cd3-11ea-9b18-3a23ece12596.png)
更新之后app没提示

**Comment by crazecoder** [comment]
![image](https://user-images.githubusercontent.com/18387906/70680697-f017f300-1cd3-11ea-9858-590ddedea5ed.png)
