### ISSUE TITLE
安卓运行报错 错误: 找不到符号

### ISSUE THREAD

**Issue by abocd** [crazecoder/flutter_bugly#74]
/home/user/doo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:5: 错误: 找不到符号
import com.crazecoder.flutterbugly.FlutterBuglyPlugin;
                                  ^
  符号:   类 FlutterBuglyPlugin
  位置: 程序包 com.crazecoder.flutterbugly
/home/user/doo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: 错误: 找不到符号
    FlutterBuglyPlugin.registerWith(registry.registrarFor("com.crazecoder.flutterbugly.FlutterBuglyPlugin"));
    ^
  符号:   变量 FlutterBuglyPlugin
  位置: 类 GeneratedPluginRegistrant
2 个错误

请问这个是什么原因呢

**Comment by crazecoder** [comment]
试过flutter clean了吗？
