### ISSUE TITLE
你已放弃让SDK来处理策略是什么情况导致的，怎么处理

### ISSUE THREAD

**Issue by YunhuiLiu140502** [crazecoder/flutter_bugly#75]
你已放弃让SDK来处理策略是什么情况导致的，怎么处理

I/CrashReport(  480): 你已放弃让SDK来处理策略
I/CrashReport(  480): betaStrategy is null
I/CrashReport(  480): 用户自定义activity，创建task失败 [strategy:null]

**Comment by crazecoder** [comment]
忽略它
