### ISSUE TITLE
UpgradeInfo一直为null

### ISSUE THREAD

**Issue by huluxia** [crazecoder/flutter_bugly#78]
@说明书和您的demo都看了几次,操作起来UpgradeInfo一直为null
![bugly1](https://user-images.githubusercontent.com/18514186/73713044-f1e7bb00-4746-11ea-8cc4-cb79aeaf1da6.png)
![bugly2](https://user-images.githubusercontent.com/18514186/73713051-f6ac6f00-4746-11ea-97f6-1c427e7220ce.png)

**Comment by kingGang** [comment]
我也遇到了同样的问题！这个方法FlutterBugly.checkUpgrade(isManual:true,isSilence:true),UpgradeInfo  一直返回null。

下面是打印出来的log
D/CrashReport(31776): [Upload] Bugly version from headers is: bugly/1.0
D/CrashReport(31776): [Upload] Status from server is 0 (pid=31776 | tid=31843).
D/CrashReport(31776): [Upload] Received 127 bytes
D/CrashReport(31776): [Util] Unzip 111 bytes data with type Gzip
D/CrashReport(31776): [Upload] Response cmd is: 0, length of sBuffer is: 0
D/CrashReport(31776): [Database] insert t_pf success.
I/CrashReport(31776): [Upload] Success: 804
D/CrashReport(31776): [UploadManager] Local network consume: 30 KB
D/CrashReport(31776): [Database] deleted t_lr data 1
D/CrashReport(31776): [Database] insert t_lr success.
D/CrashReport(31776): [UploadManager] Network total consume: 31 KB
I/CrashReport(31776): upload succ:[804] [sended 775] [recevied 127]
I/CrashReport(31776): 你已放弃让SDK来处理策略
I/CrashReport(31776): betaStrategy is null
I/CrashReport(31776): 用户自定义activity，创建task失败 [strategy:null]

**Comment by Unicellular-SU** [comment]
> 我也遇到了同样的问题！这个方法FlutterBugly.checkUpgrade(isManual:true,isSilence:true),UpgradeInfo 一直返回null。
> 
> 下面是打印出来的log
> D/CrashReport(31776): [Upload] Bugly version from headers is: bugly/1.0
> D/CrashReport(31776): [Upload] Status from server is 0 (pid=31776 | tid=31843).
> D/CrashReport(31776): [Upload] Received 127 bytes
> D/CrashReport(31776): [Util] Unzip 111 bytes data with type Gzip
> D/CrashReport(31776): [Upload] Response cmd is: 0, length of sBuffer is: 0
> D/CrashReport(31776): [Database] insert t_pf success.
> I/CrashReport(31776): [Upload] Success: 804
> D/CrashReport(31776): [UploadManager] Local network consume: 30 KB
> D/CrashReport(31776): [Database] deleted t_lr data 1
> D/CrashReport(31776): [Database] insert t_lr success.
> D/CrashReport(31776): [UploadManager] Network total consume: 31 KB
> I/CrashReport(31776): upload succ:[804] [sended 775] [recevied 127]
> I/CrashReport(31776): 你已放弃让SDK来处理策略
> I/CrashReport(31776): betaStrategy is null
> I/CrashReport(31776): 用户自定义activity，创建task失败 [strategy:null]

我也是这样，请问您解决了吗

**Comment by kingGang** [comment]
> > 我也遇到了同样的问题！这个方法FlutterBugly.checkUpgrade(isManual:true,isSilence:true),UpgradeInfo 一直返回null。
> > 下面是打印出来的log
> > D/CrashReport(31776): [Upload] Bugly version from headers is: bugly/1.0
> > D/CrashReport(31776): [Upload] Status from server is 0 (pid=31776 | tid=31843).
> > D/CrashReport(31776): [Upload] Received 127 bytes
> > D/CrashReport(31776): [Util] Unzip 111 bytes data with type Gzip
> > D/CrashReport(31776): [Upload] Response cmd is: 0, length of sBuffer is: 0
> > D/CrashReport(31776): [Database] insert t_pf success.
> > I/CrashReport(31776): [Upload] Success: 804
> > D/CrashReport(31776): [UploadManager] Local network consume: 30 KB
> > D/CrashReport(31776): [Database] deleted t_lr data 1
> > D/CrashReport(31776): [Database] insert t_lr success.
> > D/CrashReport(31776): [UploadManager] Network total consume: 31 KB
> > I/CrashReport(31776): upload succ:[804] [sended 775] [recevied 127]
> > I/CrashReport(31776): 你已放弃让SDK来处理策略
> > I/CrashReport(31776): betaStrategy is null
> > I/CrashReport(31776): 用户自定义activity，创建task失败 [strategy:null]
> 
> 我也是这样，请问您解决了吗

检查构建号，构建号一定要比线上的构建和高

**Comment by Unicellular-SU** [comment]
> > > 我也遇到了同样的问题！这个方法FlutterBugly.checkUpgrade(isManual:true,isSilence:true),UpgradeInfo 一直返回null。
> > > 下面是打印出来的log
> > > D/CrashReport(31776): [Upload] Bugly version from headers is: bugly/1.0
> > > D/CrashReport(31776): [Upload] Status from server is 0 (pid=31776 | tid=31843).
> > > D/CrashReport(31776): [Upload] Received 127 bytes
> > > D/CrashReport(31776): [Util] Unzip 111 bytes data with type Gzip
> > > D/CrashReport(31776): [Upload] Response cmd is: 0, length of sBuffer is: 0
> > > D/CrashReport(31776): [Database] insert t_pf success.
> > > I/CrashReport(31776): [Upload] Success: 804
> > > D/CrashReport(31776): [UploadManager] Local network consume: 30 KB
> > > D/CrashReport(31776): [Database] deleted t_lr data 1
> > > D/CrashReport(31776): [Database] insert t_lr success.
> > > D/CrashReport(31776): [UploadManager] Network total consume: 31 KB
> > > I/CrashReport(31776): upload succ:[804] [sended 775] [recevied 127]
> > > I/CrashReport(31776): 你已放弃让SDK来处理策略
> > > I/CrashReport(31776): betaStrategy is null
> > > I/CrashReport(31776): 用户自定义activity，创建task失败 [strategy:null]
> > 
> > 
> > 我也是这样，请问您解决了吗
> 
> 检查构建号，构建号一定要比本地的版本大

感谢恢复，已经解决了。。但是我什么都没做，用模拟器跑了一下就接收到了。。。估计是bugly下发策略的问题
