### ISSUE TITLE
编译报错：D8: Program type already present: android.support.v4.app.INotificationSideChannel

### ISSUE THREAD

**Issue by ycads** [crazecoder/flutter_bugly#8]
大家好，请帮忙分析一下这个如何解决，谢谢！不加入bugly就没有问题。
D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

@crazecoder

**Comment by crazecoder** [comment]
androidx和support不要混用

**Comment by ycads** [comment]
> androidx和support不要混用

谢谢！但是flutter_bugly是使用到androidx的吧，如何在非androidx使用呢？

**Comment by crazecoder** [comment]
都适配了，readme有说明

**Comment by ycads** [comment]
> 都适配了，readme有说明

已解决，非常感谢！
