### ISSUE TITLE
执行flutter build apk 报错

### ISSUE THREAD

**Issue by wow-lc** [crazecoder/flutter_bugly#82]
项目flutter run 可以运行，但是打包一直报错

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_bugly:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade   
   > Android resource linking failed
     C:\Users\lc\.gradle\caches\transforms-2\files-2.1\a37d7647168a444700eada6776a3f208\appcompat-1.0.0\res\values-v28\values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\lc\.gradle\caches\transforms-2\files-2.1\a37d7647168a444700eada6776a3f208\appcompat-1.0.0\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\lc\.gradle\caches\transforms-2\files-2.1\7faf2ad74a0b9932e38d86e684646e95\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
     C:\Users\lc\.gradle\caches\transforms-2\files-2.1\7faf2ad74a0b9932e38d86e684646e95\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      27.3s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try
using Jetfier to solve the incompatibility.
Building plugin flutter_bugly...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    1.4s
√ Built build\app\outputs\repo.
C:\Users\lc\Desktop\flutter_sleep\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:17: ����: �Ҳ�������
      com.crazecoder.flutterbugly.FlutterBuglyPlugin.registerWith(shimPluginRegistry.registrarFor("com.crazecoder.flutterbugly.FlutterBuglyPlugin"));
                                 ^
  ����:   �� FlutterBuglyPlugin
  λ��: ����� com.crazecoder.flutterbugly
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       2.7s
Gradle task assembleRelease failed with exit code 1

**Comment by ZMNOTZ** [comment]
我也遇到了，你解决了嘛？
