### ISSUE TITLE
 MissingPluginException(No implementation found for method checkUpgrade on channel crazecoder/flutter_bugly)

### ISSUE THREAD

**Issue by gaoyong06** [crazecoder/flutter_bugly#83]
实现一个检查更新的功能，使用checkUpgrade 
写了一个demo跑了下，报下面的错，看起来是插件内部报错了

demo代码片段：

`
onTap: () {

              /// 手动检查更新
              ///参考文档：
              ///   https://github.com/crazecoder/flutter_bugly/blob/7b71c8644085ed843db61b75aa868fbfd4d85af3/example/lib/main.dart
              ///   https://github.com/crazecoder/flutter_bugly/blob/e49b832dfe42212951313ed104ffc88a2b0e990d/lib/src/bean/upgrade_info.dart
              FlutterBugly.checkUpgrade(isManual: true, isSilence: false, useCache: false).then((UpgradeInfo info) {

                if (info != null && info.id != null) {
                  //upgradeType = 1;//2为强制更新
                  String message = sprintf('title: %s newFeature: %s apkUrl: %s upgradeType: %s versionCode: %s versionName : %s publishTime: %s', [
                    info.title, 
                    info.newFeature,
                    info.apkUrl,
                    info.upgradeType,
                    info.versionCode,
                    info.versionName,
                    info.publishTime,
                  ]);
                  print("检查更新信息： " + message);
                  Fluttertoast.showToast(msg: message,);
                }
              });
            },

`

错误日志：

E/flutter (19895): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method checkUpgrade on channel crazecoder/flutter_bugly)
E/flutter (19895): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (19895): <asynchronous suspension>
E/flutter (19895): #1      FlutterBugly.checkUpgrade (package:flutter_bugly/src/flutter_bugly.dart:109:42)
E/flutter (19895): #2      SettingIndexPage.build.<anonymous closure> (package:demo_app/pages/setting/SettingIndexPage.dart:118:28)
E/flutter (19895): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (19895): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (19895): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19895): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (19895): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (19895): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (19895): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (19895): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (19895): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (19895): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (19895): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (19895): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (19895): #15     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (19895): #16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (19895): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (19895): #18     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (19895): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)

**Comment by crazecoder** [comment]
flutter clean再试试



---Original---
