### ISSUE TITLE
请问如何支持web端？

### ISSUE THREAD

**Issue by bianxiang** [crazecoder/flutter_bugly#84]
我现在用flutter把app运行成web，发现bugly这个库仅支持安卓和ios，导致生成的web打不开，请问如何支持web端？

**Comment by crazecoder** [comment]
不支持web



---原始邮件---
发件人: "bx"<notifications@github.com&gt;
发送时间: 2020年4月29日(周三) 晚上6:13
收件人: "crazecoder/flutter_bugly"<flutter_bugly@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [crazecoder/flutter_bugly] 请问如何支持web端？ (#84)




 
我现在用flutter把app运行成web，发现bugly这个库仅支持安卓和ios，导致生成的web打不开，请问如何支持web端？
