### ISSUE TITLE
ios的Swift版本中依赖库报错

### ISSUE THREAD

**Issue by CYZZ** [crazecoder/flutter_bugly#89]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Bugly", referenced from:
      objc-class-ref in flutter_bugly(FlutterBuglyPlugin.o)
  "_OBJC_CLASS_$_BuglyConfig", referenced from:
      objc-class-ref in flutter_bugly(FlutterBuglyPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by eddy201212** [comment]
有遇到一样问题的吗？

**Comment by niteapps** [comment]
进入项目 ios->pods->Bugly->   将Bugly.framework 拖到 Xcode->Runner->Targets->Build Phases->Link Binary With Libraries
